[connections.snowflake]
account = "ANB60338"
user = "mno "
password = "BADGEbadge2"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
